In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression


In [2]:
data = pd.read_csv(r"D:\University\Nhap_mon_tri_tue_nhan_tao\project\dataset\diabetes_optimal.csv")

# data = pd.read_csv(r"D:\University\Nhap_mon_tri_tue_nhan_tao\project\dataset\clean_diabetes.csv")

X = data.drop(columns=["Outcome"])
y = data["Outcome"]

In [3]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y   
)


In [4]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)


In [5]:
log_reg = LogisticRegression(max_iter=1000, random_state=42)

log_reg.fit(X_train_scaled, y_train)

y_pred_log = log_reg.predict(X_test_scaled)

print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_log))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_log))
print("Classification Report:")
print(classification_report(y_test, y_pred_log))


Logistic Regression Accuracy: 0.7077922077922078
Confusion Matrix:
[[79 21]
 [24 30]]
Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.79      0.78       100
           1       0.59      0.56      0.57        54

    accuracy                           0.71       154
   macro avg       0.68      0.67      0.67       154
weighted avg       0.70      0.71      0.71       154



In [6]:
param_grid_log = {
    "C": [0.01, 0.1, 1, 10, 100],
    "solver": ["liblinear", "lbfgs"],
    "penalty": ["l2"]
}

grid_log = GridSearchCV(
    LogisticRegression(max_iter=1000, random_state=42),
    param_grid_log,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

grid_log.fit(X_train_scaled, y_train)

print("Best Logistic Regression Score:", grid_log.best_score_)
print("Best Logistic Regression Params:", grid_log.best_params_)

best_log_model = grid_log.best_estimator_
y_pred_best_log = best_log_model.predict(X_test_scaled)

print("Test Accuracy:", accuracy_score(y_test, y_pred_best_log))
print(classification_report(y_test, y_pred_best_log))

Best Logistic Regression Score: 0.7948020791683327
Best Logistic Regression Params: {'C': 0.1, 'penalty': 'l2', 'solver': 'lbfgs'}
Test Accuracy: 0.7077922077922078
              precision    recall  f1-score   support

           0       0.77      0.79      0.78       100
           1       0.59      0.56      0.57        54

    accuracy                           0.71       154
   macro avg       0.68      0.67      0.67       154
weighted avg       0.70      0.71      0.71       154



In [7]:
dt_model = DecisionTreeClassifier(
    criterion="gini",
    max_depth=4,
    random_state=42
)

dt_model.fit(X_train, y_train)

y_pred_dt = dt_model.predict(X_test)

print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_dt))
print("Classification Report:")
print(classification_report(y_test, y_pred_dt))

Decision Tree Accuracy: 0.8376623376623377
Confusion Matrix:
[[89 11]
 [14 40]]
Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.89      0.88       100
           1       0.78      0.74      0.76        54

    accuracy                           0.84       154
   macro avg       0.82      0.82      0.82       154
weighted avg       0.84      0.84      0.84       154



In [8]:
param_grid_dt = {
    "criterion": ["gini", "entropy"],
    "max_depth": [2, 3, 4, 5, 6, 7, 8, None],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4, 6]
}

grid_dt = GridSearchCV(
    DecisionTreeClassifier(random_state=42),
    param_grid_dt,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

grid_dt.fit(X_train, y_train)

print("Best Decision Tree Score:", grid_dt.best_score_)
print("Best Decision Tree Params:", grid_dt.best_params_)

best_dt_model = grid_dt.best_estimator_
y_pred_best_dt = best_dt_model.predict(X_test)

print("Test Accuracy:", accuracy_score(y_test, y_pred_best_dt))
print(classification_report(y_test, y_pred_best_dt))

Best Decision Tree Score: 0.8599493535918965
Best Decision Tree Params: {'criterion': 'gini', 'max_depth': 8, 'min_samples_leaf': 2, 'min_samples_split': 10}
Test Accuracy: 0.8441558441558441
              precision    recall  f1-score   support

           0       0.89      0.87      0.88       100
           1       0.77      0.80      0.78        54

    accuracy                           0.84       154
   macro avg       0.83      0.83      0.83       154
weighted avg       0.85      0.84      0.84       154



In [9]:
knn = KNeighborsClassifier(
    n_neighbors=5,
    metric="minkowski"
)

knn.fit(X_train_scaled, y_train)

y_pred = knn.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))


Accuracy: 0.8116883116883117

Classification Report:

              precision    recall  f1-score   support

           0       0.85      0.86      0.86       100
           1       0.74      0.72      0.73        54

    accuracy                           0.81       154
   macro avg       0.79      0.79      0.79       154
weighted avg       0.81      0.81      0.81       154


Confusion Matrix:

[[86 14]
 [15 39]]


In [10]:
param_grid = {
    "n_neighbors": np.arange(1, 31),
    "weights": ["uniform", "distance"],
    "metric": ["euclidean", "manhattan"]
}

grid = GridSearchCV(
    KNeighborsClassifier(),
    param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

grid.fit(X_train_scaled, y_train)

best_knn = grid.best_estimator_

print("Best CV Accuracy:", grid.best_score_)
print("Best Parameters:", grid.best_params_)

y_pred_best = best_knn.predict(X_test_scaled)

print("Test Accuracy:", accuracy_score(y_test, y_pred_best))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_best))


Best CV Accuracy: 0.8598960415833667
Best Parameters: {'metric': 'manhattan', 'n_neighbors': np.int64(17), 'weights': 'uniform'}
Test Accuracy: 0.8506493506493507

Classification Report:

              precision    recall  f1-score   support

           0       0.87      0.90      0.89       100
           1       0.80      0.76      0.78        54

    accuracy                           0.85       154
   macro avg       0.84      0.83      0.83       154
weighted avg       0.85      0.85      0.85       154



In [11]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

models_result = {
    "KNN": y_pred_best,
    "Logistic Regression": y_pred_best_log,
    "Decision Tree": y_pred_best_dt
}

for name, y_pred in models_result.items():
    print("Model:", name)
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred))
    print("Recall:", recall_score(y_test, y_pred))
    print("F1-score:", f1_score(y_test, y_pred))
    print("-" * 40)

Model: KNN
Accuracy: 0.8506493506493507
Precision: 0.803921568627451
Recall: 0.7592592592592593
F1-score: 0.780952380952381
----------------------------------------
Model: Logistic Regression
Accuracy: 0.7077922077922078
Precision: 0.5882352941176471
Recall: 0.5555555555555556
F1-score: 0.5714285714285714
----------------------------------------
Model: Decision Tree
Accuracy: 0.8441558441558441
Precision: 0.7678571428571429
Recall: 0.7962962962962963
F1-score: 0.7818181818181819
----------------------------------------
